# Spring-Cloud-PetClinic-Service

# ApplicationVersion
application.version=spring-cloud-petclinic-service:2.8.50-RELEASE

# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true

# Internationalization
spring.messages.basename=messages/messages


# Actuator
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,info

#management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.exclude=httptrace
# management.endpoint.health.probes.enabled=true
# management.health.livenessState.enabled=true
# management.health.readinessState.enabled=true
# management.endpoints.web.exposure.exclude=heapdump
# management.endpoint.heapdump.enabled=false

# management.endpoint.metrics.enabled=true
# management.endpoint.prometheus.enabled=true
# management.metrics.export.prometheus.enabled=true

# management.endpoint.env.show-values=ALWAYS

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h
