#
# maven profile: postgres
#
database=postgres

# De-Reference an IP, if supplied.  Makes life easier, especially for K8s.
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://${POSTGRES_IP:localhost}/petclinic}
spring.datasource.username=${POSTGRES_USER:dbuser}
spring.datasource.password=${POSTGRES_PASS:securepassword123}

# SQL is written to be idempotent so this is safe
spring.sql.init.mode=always
