# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: maven-build

on:
  # push:
  #   branches: [ "*" ]

  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'Full'
        type: choice
        options:
          - 'Full'
          - 'Quick'

      target_branch:
              description: 'Branch'
              required: true
              default: 'main'
              type: choice
              options:
                - main
                - spring-framework-to-6.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: SetUp JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    

    - name: Select Branch
      run: |
        echo "Building on branch: ${{ github.event.inputs.target_branch }}"
        git checkout ${{ github.event.inputs.target_branch }}
        git branch -a

    - name: Maven Build
      run: |
        echo "Building on branch: ${{ github.event.inputs.target_branch }}"
        echo "Current Directory: $(pwd)"
        cd /projects/spring-cloud-petclinic-service
        echo "Current Directory: $(pwd)"
        mvn clean compile package install -D"skipTests=true"        


