# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: maven-build

on:
  # push:
  #   branches: [ "*" ]

  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'Full'
        type: choice
        options:
          - 'Base'
          - 'Full'          

      target_branch:
              description: 'Branch'
              required: true
              default: 'spring-framework-to-6.2.3'
              type: choice
              options:
                - main
                - spring-framework-to-6.2.3
      app_version:
        description: 'Application Version'
        required: true
        default: 'latest'

      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'latest'

env:
  MVN_ARGS_BASE: 'clean compile package install -D"skipTests=true"'
  MVN_ARGS_FULL: 'clean compile package install -D"skipTests=true" -P build-img -Dspring-boot.build-image.imagePlatform=linux/amd64'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: SetUp JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: SetUp Docker
      # Use the specific action for installing a custom Docker version
      uses: docker/setup-docker-action@v1
      with:
        # Specify the desired version number (e.g., 'v27.4.0')
        version: 'v28.5.1' #v28.0.4

    - name: Cache the Maven packages to speed up build
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2    

    - name: Select Branch
      run: |
        echo "Building on branch: ${{ github.event.inputs.target_branch }}"
        git checkout ${{ github.event.inputs.target_branch }}
        git branch -a

    - name: Confirm Docker Version
      run: |
        echo "Docker Version:"
        docker version

    - name: Clean Up Docker
      run: |        
        docker system prune -af

    - name: Maven Build Validation
      run: |
        echo "Building on branch: ${{ github.event.inputs.target_branch }}"
        cd projects/spring-cloud-petclinic-service
        echo "Current Directory: $(pwd)"
        mvn validate

    - name: Maven Build
      run: |
        echo "Building on branch: ${{ github.event.inputs.target_branch }}"
        cd projects/spring-cloud-petclinic-service
        echo "Current Directory: $(pwd)"
        mvn ${{ github.event.inputs.build_type == 'Base' && env.MVN_ARGS_BASE || env.MVN_ARGS_FULL }}

    - name: GHCR Docker Login
      if: ${{ github.event.inputs.build_type == 'Full' }}    
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}    

    - name: GHCR Image Push
      if: ${{ github.event.inputs.build_type == 'Full' }}
      run: |
        echo "Pushing Docker Image to GHCR"
        cd projects/spring-cloud-petclinic-service
        echo "Current Directory: $(pwd)"
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/spring-cloud-petclinic-service:${{ github.event.inputs.image_tag }}"
        docker tag docker.io/library/spring-cloud-petclinic-service:${{ github.event.inputs.app_version }} $IMAGE_NAME
        docker image list
        docker push $IMAGE_NAME
